from enum import Enum


class DocCategory(Enum):
    TECHNICAL_CERTIFICATE = "TECHNICAL_CERTIFICATE"
    PUBLIC_LIABILITY = "PUBLIC_LIABILITY"
    PERSONAL_CERTIFICATE = "PERSONAL_CERTIFICATE"
    OTHER_RECOGNITION = "OTHER_RECOGNITION"
    RECERTIFICATION_LETTER = "RECERTIFICATION_LETTER"
    SSM_PROFILE = "SSM_PROFILE"


class InterceptType(Enum):
    NONE = None
    WRONG_DOC = "WRONG_DOC"
    WRONG_STANDARD = "WRONG_STANDARD"
    SSM_UPLOAD = "SSM_UPLOAD"
    RECERTIFICATION_LETTER = "RECERTIFICATION_LETTER"
    SUPPLIER_MISMATCH = "SUPPLIER_MISMATCH"
    EXPIRED = "EXPIRED"
    PL_INSUFFICIENT = "PL_INSUFFICIENT"
    MULTIPLE_CERTIFICATES = "MULTIPLE_CERTIFICATES"
    FIELD_MISMATCH = "FIELD_MISMATCH"
    PERMANENT_DATE_REVISION = "PERMANENT_DATE_REVISION"


class ExpiryStatus(Enum):
    VALID = "VALID"
    EXPIRED = "EXPIRED"
    NOT_LISTED = "NOT_LISTED"
    PERMANENT_MATCH = "PERMANENT_MATCH"
    PERMANENT_NEEDS_REVISION = "PERMANENT_NEEDS_REVISION"
